[package]
name = "fun-uniswap-v3"
version = "0.1.0"
description = "Created with Anchor"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]
name = "fun_uniswap_v3"

[features]
default = []
cpi = ["no-entrypoint"]
no-entrypoint = []
no-idl = []
no-log-ix-name = []
idl-build = ["anchor-lang/idl-build", "anchor-spl/idl-build"]


[dependencies]
anchor-lang = { version = "0.31.0", features = ["init-if-needed"] }
anchor-spl = { version = "0.31.0", features = ["metadata", "memo"] }
uint = { git = "https://github.com/raydium-io/parity-common", package = "uint" }
arrayref = { version = "0.3.6" }
bytemuck = { version = "1.19.0", features = ["derive", "min_const_generics"] }

[dev-dependencies]
proptest = "1.0"
quickcheck = "0.9"
rand = "0.8.5"

