[package]
name = "practice"
version = "0.1.0"
edition = "2021"

[dependencies]
bytemuck = { version = "1.19.0", features = ["derive", "min_const_generics"] }
solana-program = "3.0.0"

[dev-dependencies]
solana-client = "2.1.0"
solana-sdk = "2.1.0"

